# XXX: It doesn't work:
#
# > schema.lua:3007 E> ER_UNSUPPORTED_PRIV: Unsupported universe
# > privilege 'super'

# Demonstration of the credentials section format.
#
# A privilege (rights to do something) may be granted to a role
# or a user.
#
# A privilege is a composition of permissions and objects.
#
# {{permissions}}
# - super
# - read
# - write
# - execute
# - create
# - alter
# - drop
# - usage
# - session
#
# {{privilege objects}}
# - universe
# - space
# - function
# - sequence
#
# TODO: Describe permissions appliablity to particular objects.
#
# TODO: Explain meaning of 'usage' and 'session' permissions.
#
# {{built-in roles}}
# - public
# - replication
# - super
#
# TODO: Describe what exactly the built-in roles give.
#
# {{built-in users}}
# - guest
# - admin
#
# TODO: Explain default permissions and password setting for the
# built-in users.

config:
  version: 3.0.0

credentials:
  roles:
    # A role that allows direct reading from a space, but requires
    # to call a function for modifications.
    api_access:
      privileges:
      - permissions: [read]
        spaces: [myspace]
      - permissions: [execute]
        functions: [mufunc]

    # The 'allow everything' role. It is just like the built-in
    # 'super' role.
    audit:
      privileges:
      - permissions: [super]
        universe: true

    # A role can inherit all privileges from a list of given
    # roles.
    cdc:
      roles: [replication]

  users:
    # A user definition is quite same as a role definition, but
    # has extra 'password' field.
    #
    # Let's create a user for replication.
    replicator:
      password:
        plain: 'topsecret'
      roles: [replication]

    # Create a user for external clients.
    client:
      password:
        plain: 'secret'
      roles: [api_access]

    # Define a user with super power.
    #
    # The 'admin' user is built-in and has all the rights by
    # default, but they're granted here explicitly for the
    # demonstration purposes.
    admin:
      password:
        plain: 'topsecret'
      privileges:
      - permissions: [super]
        universe: true

    # A restricted user to call monitoring functions.
    monitor:
      privileges:
      - permissions: [execute]
        functions:
        - box.info
        - box.stat
        - metrics.getmetrics

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'
  advertise: 'replicator:topsecret@unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              rw: true
          instance-002: {}
          instance-003: {}
