credentials:
  users:
    me:
      passwd:
        plain: secret
      grant: [super]

groups:
  g:
    replicasets:
      r:
        instances:
          i:
            iproto:
              listen: localhost:3301
