# Demonstration of the credentials section format.
#
# A privilege (rights to do something) may be granted to a role
# or a user.
#
# A privilege is a composition of permissions and objects.
#
# {{permissions}}
# - read
# - write
# - execute
# - create
# - alter
# - drop
# - usage
# - session
#
# {{privilege objects}}
# - universe
# - space (NYI)
# - function (NYI)
# - sequence (NYI)
#
# TODO: Describe permissions appliablity to particular objects.
#
# TODO: Explain meaning of 'usage' and 'session' permissions.
#
# {{built-in roles}}
# - public
# - replication
# - super
#
# TODO: Describe what exactly the built-in roles give.
#
# {{built-in users}}
# - guest
# - admin
#
# TODO: Explain default permissions and password setting for the
# built-in users.

credentials:
  roles:
    # A role that allows direct reading from a space, but requires
    # to call a function for modifications.
    api_access:
      privileges: []
      # TODO: NYI
      #- permissions: [read]
      #  spaces: [myspace]
      #- permissions: [execute]
      #  functions: [mufunc]

    # The 'allow everything' role. It is just like the built-in
    # 'super' role.
    audit:
      privileges:
      - permissions: [read, write, execute, create, alter, drop]
        universe: true

    # A role can inherit all privileges from a list of given
    # roles.
    cdc:
      roles: [replication]

  users:
    # A user definition is quite same as a role definition, but
    # has extra 'password' field.
    #
    # Let's create a user for replication.
    replicator:
      password:
        plain: 'topsecret'
      roles: [replication]

    # Create a user for external clients.
    client:
      password:
        plain: 'secret'
      # Super is here purely for testing purposes.
      roles: [api_access, super]

    # Set a password for the built-in admin user.
    #
    # The 'admin' user has all the rights by default.
    admin:
      password:
        plain: 'topsecret'

    # A restricted user to call monitoring functions.
    monitor:
      password:
        plain: 'secret'
      privileges: []
      # TODO: NYI
      #- permissions: [execute]
      #  functions:
      #  - box.info
      #  - box.stat
      #  - metrics.getmetrics

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'
  advertise: 'replicator:topsecret@unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              rw: true
          instance-002: {}
          instance-003: {}
