config:
  etcd:
    prefix: /foo
    endpoints:
    - http://localhost:2379

groups:
  g:
    replicasets:
      r:
        instances:
          i:
            iproto:
              listen: localhost:3301
