database:
  wal:
    dir: '{{ instance_name }}'
  snapshot:
    dir: '{{ instance_name }}'
iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'

groups:
  g:
    replicasets:
      r:
        instances:
          i: {}
          k: {}
