credentials:
  users:
    guest:
      roles: [super]

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'

console:
  socket: '{{ instance_name }}.control'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              rw: true
