config:
  version: 3.0.0

credentials:
  users:
    guest:
      roles: [super]

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              rw: true
