credentials:
  users:
    guest:
      roles: [super]
      privileges:
      - spaces: [_space]

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
