config:
  version: 3.0.0
  etcd:
    prefix: /foo
    endpoints:
    - http://localhost:2379

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'
  advertise: 'replicator:topsecret@unix/:./{{ instance_name }}.iproto'
