local schema = require('internal.config.utils.schema')

-- List of annotations:
--
-- * type (string)
--
--   Scalar type.
--
-- * enterprise_edition (boolean)
--
--   Available only in Tarantool Enterprise Edition.
--
-- * default (any)
--
--   Default value.
--
-- * scope ('global', 'group', 'repicaset', 'instance')
--
--   A place of an instance config option in in the cluster config
--   hierarchy.
--
-- * box_cfg (string)
--
--   A name of the corresponding box.cfg() option.
--
-- * box_cfg_nondynamic (boolean)
--
--   `true` if the option can only be set at first box.cfg() call
--   and cannot be changed by a subsequent box.cfg() call.
--
-- * allowed_values
--
--   A list of allowed values.
--
-- * mkdir (boolean)
--
--   Create the given directory before box.cfg().
--
-- * mk_parent_dir (booelan)
--
--   Create a parent directry for the given file before box.cfg().

return schema.new('instance_config', schema.record({}))
